modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]]
modId = "phantasm"
version = "1.1"
displayName = "End's Phantasm"
credits = "Ported to NeoForge with love by SashaKYotoz:)"
logoFile = "icon.png"
authors = "Lyof"
description = "The vanilla friendly End update we were all waiting for"

[[mixins]]
config = "phantasm.mixins.json"

[[dependencies.phantasm]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.phantasm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
